# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Michael Ngo" # Site name or title
logo: "/assets/face.jpg" # Site logo
favicon: "/assets/favicon.ico"  # Site favicon
description: "My personal website" # Site description and default description
url: "https://michael-n.com" # Site url
baseurl: ""
lang: en-US
